include: package:flutter_lints/flutter.yaml
analyzer:
  plugins:
    - custom_lint

  exclude:
    - '**/lib/**/*.freezed.dart'
    - '**/lib/**/*.g.dart'
    - '**/l10n/localizations*.dart'
    
linter:
  rules:
    cancel_subscriptions
    close_sinks
    avoid_bool_literals_in_conditional_expressions
    prefer_const_constructors
    prefer_const_declarations
    prefer_const_literals_to_create_immutables
    prefer_final_in_for_each
    prefer_final_locals
    prefer_null_aware_method_calls
    sized_box_shrink_expand
    throw_in_finally
    unnecessary_lambdas
    use_decorated_box
    use_colored_box
    use_null_aware_elements
    use_string_buffers

