// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:score_counter/data/entities/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GameEntityAdapter());
    registerAdapter(GameOptionsEntityAdapter());
    registerAdapter(PlayerEntityAdapter());
    registerAdapter(PreferencesEntityAdapter());
    registerAdapter(RoundEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GameEntityAdapter());
    registerAdapter(GameOptionsEntityAdapter());
    registerAdapter(PlayerEntityAdapter());
    registerAdapter(PreferencesEntityAdapter());
    registerAdapter(RoundEntityAdapter());
  }
}
