name: Deploy to Google Play Store

on:
  push:
    tags:        
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Linter
      run: |
          dart analyze
          dart run custom_lint

    - name: Run Unit Tests
      run: |
        Y | bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)
        flutter test

    - name: Decode Keystore
      env:
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      run: |
        echo $CERTIFICATE_BASE64 | base64 --decode > keystore.jks

    - name: Build Release AppBundle
      env:
        storePassword: ${{ secrets.STOREPASSWORD }}
        keyAlias: ${{ secrets.KEYALIAS }}
        keyPassword: ${{ secrets.KEYPASSWORD }} 
      run: flutter build appbundle --obfuscate --split-debug-info='obfuscation_debug_files'

    - name: Get release file aab path
      id: releaseAab
      run: echo "aabfile=$(find build/app/outputs/bundle -name '*.aab')" >> $GITHUB_OUTPUT

    - name: Upload AppBundle to Internal Testing
      uses: wzieba/step-google-play@v3
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_AUTH }}
        packageName: com.chonli.score_counter
        source: build/app/outputs/bundle/release/app-release.aab
        track: internal