name: Deploy to Google Play Store

on:
  push:
    tags:        
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Tests
      uses: ./.github/actions/flutter-tests

    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.3.0

    - name: Decode Keystore
      env:
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      run: |
        echo $CERTIFICATE_BASE64 | base64 --decode > keystore.jks

    - name: Build Release AppBundle
      env:
        storePassword: ${{ secrets.STOREPASSWORD }}
        keyAlias: ${{ secrets.KEYALIAS }}
        keyPassword: ${{ secrets.KEYPASSWORD }} 
      run: flutter build appbundle --obfuscate --split-debug-info='obfuscation_debug_files' --build-number=$NUMBER_OF_COMMITS --build-name=$MAJOR.$MINOR.$PATCH

    - name: Upload AppBundle to Internal Testing
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH }}
        packageName: com.chonli.score_counter
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: internal
        status: draft