name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
            
    - name: Run Tests
      uses: ./.github/actions/flutter-tests

    - name: Build APK
      run: flutter build apk --debug